// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Snackbox.Api.Data;

#nullable disable

namespace Snackbox.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251228145748_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Snackbox.Api.Models.Barcode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("amount");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsLoginOnly")
                        .HasColumnType("boolean")
                        .HasColumnName("is_login_only");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("barcodes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 5.00m,
                            Code = "USER2-5EUR",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsLoginOnly = false,
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            Amount = 10.00m,
                            Code = "USER2-10EUR",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsLoginOnly = false,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            Amount = 5.00m,
                            Code = "USER3-5EUR",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsLoginOnly = false,
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            Amount = 10.00m,
                            Code = "USER3-10EUR",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsLoginOnly = false,
                            UserId = 3
                        },
                        new
                        {
                            Id = 5,
                            Amount = 0m,
                            Code = "ADMIN-LOGIN",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsLoginOnly = true,
                            UserId = 1
                        },
                        new
                        {
                            Id = 6,
                            Amount = 0m,
                            Code = "USER2-LOGIN",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsLoginOnly = true,
                            UserId = 2
                        },
                        new
                        {
                            Id = 7,
                            Amount = 0m,
                            Code = "USER3-LOGIN",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsLoginOnly = true,
                            UserId = 3
                        });
                });

            modelBuilder.Entity("Snackbox.Api.Models.BarcodeScan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("amount");

                    b.Property<int>("BarcodeId")
                        .HasColumnType("integer")
                        .HasColumnName("barcode_id");

                    b.Property<int>("PurchaseId")
                        .HasColumnType("integer")
                        .HasColumnName("purchase_id");

                    b.Property<DateTime>("ScannedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scanned_at");

                    b.HasKey("Id");

                    b.HasIndex("BarcodeId");

                    b.HasIndex("PurchaseId");

                    b.ToTable("barcode_scans");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 5.00m,
                            BarcodeId = 1,
                            PurchaseId = 1,
                            ScannedAt = new DateTime(2024, 1, 6, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            Amount = 10.00m,
                            BarcodeId = 2,
                            PurchaseId = 1,
                            ScannedAt = new DateTime(2024, 1, 6, 0, 2, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            Amount = 5.00m,
                            BarcodeId = 3,
                            PurchaseId = 2,
                            ScannedAt = new DateTime(2024, 1, 11, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Snackbox.Api.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("amount");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<DateTime>("PaidAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paid_at");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("payments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 20.00m,
                            Notes = "Initial payment",
                            PaidAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            Amount = 15.00m,
                            Notes = "Cash payment",
                            PaidAt = new DateTime(2024, 1, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 3
                        });
                });

            modelBuilder.Entity("Snackbox.Api.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("barcode");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("price");

                    b.HasKey("Id");

                    b.HasIndex("Barcode")
                        .IsUnique();

                    b.ToTable("products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Barcode = "1234567890123",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Classic salted potato chips",
                            Name = "Chips - Salt",
                            Price = 1.50m
                        },
                        new
                        {
                            Id = 2,
                            Barcode = "1234567890124",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Milk chocolate bar",
                            Name = "Chocolate Bar",
                            Price = 2.00m
                        },
                        new
                        {
                            Id = 3,
                            Barcode = "1234567890125",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Sugar-free energy drink",
                            Name = "Energy Drink",
                            Price = 2.50m
                        },
                        new
                        {
                            Id = 4,
                            Barcode = "1234567890126",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Chocolate chip cookies",
                            Name = "Cookies",
                            Price = 1.75m
                        });
                });

            modelBuilder.Entity("Snackbox.Api.Models.ProductBatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BestBeforeDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("best_before_date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("product_batches");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BestBeforeDate = new DateTime(2025, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = 1
                        },
                        new
                        {
                            Id = 2,
                            BestBeforeDate = new DateTime(2025, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = 2
                        },
                        new
                        {
                            Id = 3,
                            BestBeforeDate = new DateTime(2025, 12, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = 3
                        },
                        new
                        {
                            Id = 4,
                            BestBeforeDate = new DateTime(2025, 5, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = 4
                        });
                });

            modelBuilder.Entity("Snackbox.Api.Models.Purchase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("purchases");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompletedAt = new DateTime(2024, 1, 6, 0, 5, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2024, 1, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            CompletedAt = new DateTime(2024, 1, 11, 0, 3, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2024, 1, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 3
                        });
                });

            modelBuilder.Entity("Snackbox.Api.Models.ShelvingAction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ActionAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("action_at");

                    b.Property<int>("ProductBatchId")
                        .HasColumnType("integer")
                        .HasColumnName("product_batch_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("ProductBatchId");

                    b.ToTable("shelving_actions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActionAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProductBatchId = 1,
                            Quantity = 50,
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            ActionAt = new DateTime(2024, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProductBatchId = 1,
                            Quantity = 20,
                            Type = 1
                        },
                        new
                        {
                            Id = 3,
                            ActionAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProductBatchId = 2,
                            Quantity = 30,
                            Type = 0
                        },
                        new
                        {
                            Id = 4,
                            ActionAt = new DateTime(2024, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProductBatchId = 2,
                            Quantity = 15,
                            Type = 1
                        },
                        new
                        {
                            Id = 5,
                            ActionAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProductBatchId = 3,
                            Quantity = 40,
                            Type = 0
                        },
                        new
                        {
                            Id = 6,
                            ActionAt = new DateTime(2024, 1, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProductBatchId = 3,
                            Quantity = 25,
                            Type = 1
                        },
                        new
                        {
                            Id = 7,
                            ActionAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProductBatchId = 4,
                            Quantity = 35,
                            Type = 0
                        },
                        new
                        {
                            Id = 8,
                            ActionAt = new DateTime(2024, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProductBatchId = 4,
                            Quantity = 18,
                            Type = 1
                        });
                });

            modelBuilder.Entity("Snackbox.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean")
                        .HasColumnName("is_admin");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@snackbox.com",
                            IsAdmin = true,
                            PasswordHash = "$2a$11$hashedpassword",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "john.doe@company.com",
                            IsAdmin = false,
                            PasswordHash = "$2a$11$hashedpassword",
                            Username = "john.doe"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "jane.smith@company.com",
                            IsAdmin = false,
                            PasswordHash = "$2a$11$hashedpassword",
                            Username = "jane.smith"
                        });
                });

            modelBuilder.Entity("Snackbox.Api.Models.Barcode", b =>
                {
                    b.HasOne("Snackbox.Api.Models.User", "User")
                        .WithMany("Barcodes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Snackbox.Api.Models.BarcodeScan", b =>
                {
                    b.HasOne("Snackbox.Api.Models.Barcode", "Barcode")
                        .WithMany("Scans")
                        .HasForeignKey("BarcodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Snackbox.Api.Models.Purchase", "Purchase")
                        .WithMany("Scans")
                        .HasForeignKey("PurchaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Barcode");

                    b.Navigation("Purchase");
                });

            modelBuilder.Entity("Snackbox.Api.Models.Payment", b =>
                {
                    b.HasOne("Snackbox.Api.Models.User", "User")
                        .WithMany("Payments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Snackbox.Api.Models.ProductBatch", b =>
                {
                    b.HasOne("Snackbox.Api.Models.Product", "Product")
                        .WithMany("Batches")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Snackbox.Api.Models.Purchase", b =>
                {
                    b.HasOne("Snackbox.Api.Models.User", "User")
                        .WithMany("Purchases")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Snackbox.Api.Models.ShelvingAction", b =>
                {
                    b.HasOne("Snackbox.Api.Models.ProductBatch", "ProductBatch")
                        .WithMany("ShelvingActions")
                        .HasForeignKey("ProductBatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductBatch");
                });

            modelBuilder.Entity("Snackbox.Api.Models.Barcode", b =>
                {
                    b.Navigation("Scans");
                });

            modelBuilder.Entity("Snackbox.Api.Models.Product", b =>
                {
                    b.Navigation("Batches");
                });

            modelBuilder.Entity("Snackbox.Api.Models.ProductBatch", b =>
                {
                    b.Navigation("ShelvingActions");
                });

            modelBuilder.Entity("Snackbox.Api.Models.Purchase", b =>
                {
                    b.Navigation("Scans");
                });

            modelBuilder.Entity("Snackbox.Api.Models.User", b =>
                {
                    b.Navigation("Barcodes");

                    b.Navigation("Payments");

                    b.Navigation("Purchases");
                });
#pragma warning restore 612, 618
        }
    }
}
