// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Snackbox.Api.Data;

#nullable disable

namespace Snackbox.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260108221309_AddAchievementImages2")]
    partial class AddAchievementImages2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Snackbox.Api.Models.Achievement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("integer")
                        .HasColumnName("category");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("achievements");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = 0,
                            Code = "BIG_SPENDER_2",
                            Description = "Spent €2 or more in a single purchase",
                            ImageUrl = "<svg width=\"120\" height=\"120\" viewBox=\"0 0 120 120\" xmlns=\"http://www.w3.org/2000/svg\"><circle cx=\"60\" cy=\"60\" r=\"55\" fill=\"#FFE5B4\" stroke=\"#FF8C00\" stroke-width=\"3\"/><text x=\"60\" y=\"50\" font-size=\"36\" font-weight=\"bold\" text-anchor=\"middle\" fill=\"#FF8C00\">🍪</text><text x=\"60\" y=\"85\" font-size=\"24\" font-weight=\"bold\" text-anchor=\"middle\" fill=\"#FF8C00\">€2</text></svg>",
                            Name = "Snack Nibbler"
                        },
                        new
                        {
                            Id = 2,
                            Category = 0,
                            Code = "BIG_SPENDER_3",
                            Description = "Spent €3 or more in a single purchase",
                            ImageUrl = "<svg width=\"120\" height=\"120\" viewBox=\"0 0 120 120\" xmlns=\"http://www.w3.org/2000/svg\"><circle cx=\"60\" cy=\"60\" r=\"55\" fill=\"#FFD700\" stroke=\"#FF6347\" stroke-width=\"3\"/><text x=\"60\" y=\"50\" font-size=\"36\" font-weight=\"bold\" text-anchor=\"middle\" fill=\"#FF0000\">⚡</text><text x=\"60\" y=\"85\" font-size=\"24\" font-weight=\"bold\" text-anchor=\"middle\" fill=\"#FF0000\">€3</text></svg>",
                            Name = "Snack Attack!"
                        },
                        new
                        {
                            Id = 3,
                            Category = 0,
                            Code = "BIG_SPENDER_4",
                            Description = "Spent €4 or more in a single purchase",
                            ImageUrl = "<svg width=\"120\" height=\"120\" viewBox=\"0 0 120 120\" xmlns=\"http://www.w3.org/2000/svg\"><circle cx=\"60\" cy=\"60\" r=\"55\" fill=\"#FFB6C1\" stroke=\"#FF69B4\" stroke-width=\"3\"/><text x=\"60\" y=\"50\" font-size=\"36\" font-weight=\"bold\" text-anchor=\"middle\" fill=\"#DC143C\">🦛</text><text x=\"60\" y=\"85\" font-size=\"24\" font-weight=\"bold\" text-anchor=\"middle\" fill=\"#DC143C\">€4</text></svg>",
                            Name = "Hungry Hippo"
                        },
                        new
                        {
                            Id = 18,
                            Category = 0,
                            Code = "BIG_SPENDER_5",
                            Description = "Spent €5 or more in a single purchase",
                            ImageUrl = "<svg width=\"120\" height=\"120\" viewBox=\"0 0 120 120\" xmlns=\"http://www.w3.org/2000/svg\"><circle cx=\"60\" cy=\"60\" r=\"55\" fill=\"#E6E6FA\" stroke=\"#9370DB\" stroke-width=\"3\"/><text x=\"60\" y=\"50\" font-size=\"36\" font-weight=\"bold\" text-anchor=\"middle\" fill=\"#4B0082\">📦</text><text x=\"60\" y=\"85\" font-size=\"24\" font-weight=\"bold\" text-anchor=\"middle\" fill=\"#4B0082\">€5</text></svg>",
                            Name = "Snack Hoarder"
                        },
                        new
                        {
                            Id = 19,
                            Category = 0,
                            Code = "BIG_SPENDER_6",
                            Description = "Spent €6 or more in a single purchase",
                            ImageUrl = "<svg width=\"120\" height=\"120\" viewBox=\"0 0 120 120\" xmlns=\"http://www.w3.org/2000/svg\"><circle cx=\"60\" cy=\"60\" r=\"55\" fill=\"#B0E0E6\" stroke=\"#1E90FF\" stroke-width=\"3\"/><text x=\"60\" y=\"50\" font-size=\"36\" font-weight=\"bold\" text-anchor=\"middle\" fill=\"#00008B\">🐋</text><text x=\"60\" y=\"85\" font-size=\"24\" font-weight=\"bold\" text-anchor=\"middle\" fill=\"#00008B\">€6</text></svg>",
                            Name = "The Whale"
                        },
                        new
                        {
                            Id = 4,
                            Category = 1,
                            Code = "DAILY_BUYER_5",
                            Description = "Made 5 or more purchases in a single day",
                            ImageUrl = "<svg width=\"120\" height=\"120\" viewBox=\"0 0 120 120\" xmlns=\"http://www.w3.org/2000/svg\"><circle cx=\"60\" cy=\"60\" r=\"55\" fill=\"#87CEEB\" stroke=\"#4169E1\" stroke-width=\"3\"/><text x=\"60\" y=\"50\" font-size=\"36\" font-weight=\"bold\" text-anchor=\"middle\" fill=\"#00008B\">✈️</text><text x=\"60\" y=\"85\" font-size=\"20\" font-weight=\"bold\" text-anchor=\"middle\" fill=\"#00008B\">x5</text></svg>",
                            Name = "Frequent Flyer"
                        },
                        new
                        {
                            Id = 5,
                            Category = 1,
                            Code = "DAILY_BUYER_10",
                            Description = "Made 10 or more purchases in a single day",
                            ImageUrl = "<svg width=\"120\" height=\"120\" viewBox=\"0 0 120 120\" xmlns=\"http://www.w3.org/2000/svg\"><circle cx=\"60\" cy=\"60\" r=\"55\" fill=\"#FFDAB9\" stroke=\"#D2691E\" stroke-width=\"3\"/><text x=\"60\" y=\"50\" font-size=\"36\" font-weight=\"bold\" text-anchor=\"middle\" fill=\"#8B4513\">🏃</text><text x=\"60\" y=\"85\" font-size=\"18\" font-weight=\"bold\" text-anchor=\"middle\" fill=\"#8B4513\">x10</text></svg>",
                            Name = "Snack Marathon"
                        },
                        new
                        {
                            Id = 20,
                            Category = 1,
                            Code = "DAILY_BUYER_3",
                            Description = "Made 3 purchases in a single day",
                            ImageUrl = "<svg width=\"120\" height=\"120\" viewBox=\"0 0 120 120\" xmlns=\"http://www.w3.org/2000/svg\"><circle cx=\"60\" cy=\"60\" r=\"55\" fill=\"#98FB98\" stroke=\"#228B22\" stroke-width=\"3\"/><text x=\"60\" y=\"50\" font-size=\"36\" font-weight=\"bold\" text-anchor=\"middle\" fill=\"#006400\">🎩</text><text x=\"60\" y=\"85\" font-size=\"20\" font-weight=\"bold\" text-anchor=\"middle\" fill=\"#006400\">x3</text></svg>",
                            Name = "Hat Trick"
                        },
                        new
                        {
                            Id = 6,
                            Category = 2,
                            Code = "STREAK_DAILY_3",
                            Description = "Made a purchase 3 days in a row",
                            ImageUrl = "<svg width=\"120\" height=\"120\" viewBox=\"0 0 120 120\" xmlns=\"http://www.w3.org/2000/svg\"><circle cx=\"60\" cy=\"60\" r=\"55\" fill=\"#FFA07A\" stroke=\"#FF4500\" stroke-width=\"3\"/><text x=\"60\" y=\"55\" font-size=\"40\" font-weight=\"bold\" text-anchor=\"middle\" fill=\"#8B0000\">🔥</text><text x=\"60\" y=\"85\" font-size=\"20\" font-weight=\"bold\" text-anchor=\"middle\" fill=\"#8B0000\">3d</text></svg>",
                            Name = "Three-peat"
                        },
                        new
                        {
                            Id = 7,
                            Category = 2,
                            Code = "STREAK_DAILY_7",
                            Description = "Made a purchase 7 days in a row",
                            ImageUrl = "<svg width=\"120\" height=\"120\" viewBox=\"0 0 120 120\" xmlns=\"http://www.w3.org/2000/svg\"><circle cx=\"60\" cy=\"60\" r=\"55\" fill=\"#FFD700\" stroke=\"#FF8C00\" stroke-width=\"3\"/><text x=\"60\" y=\"55\" font-size=\"40\" font-weight=\"bold\" text-anchor=\"middle\" fill=\"#B8860B\">⚔️</text><text x=\"60\" y=\"85\" font-size=\"20\" font-weight=\"bold\" text-anchor=\"middle\" fill=\"#B8860B\">7d</text></svg>",
                            Name = "Week Warrior"
                        },
                        new
                        {
                            Id = 8,
                            Category = 2,
                            Code = "STREAK_WEEKLY_4",
                            Description = "Made at least one purchase per week for 4 weeks",
                            ImageUrl = "<svg width=\"120\" height=\"120\" viewBox=\"0 0 120 120\" xmlns=\"http://www.w3.org/2000/svg\"><circle cx=\"60\" cy=\"60\" r=\"55\" fill=\"#90EE90\" stroke=\"#32CD32\" stroke-width=\"3\"/><text x=\"60\" y=\"55\" font-size=\"40\" font-weight=\"bold\" text-anchor=\"middle\" fill=\"#006400\">📆</text><text x=\"60\" y=\"85\" font-size=\"18\" font-weight=\"bold\" text-anchor=\"middle\" fill=\"#006400\">4w</text></svg>",
                            Name = "Monthly Muncher"
                        },
                        new
                        {
                            Id = 21,
                            Category = 2,
                            Code = "STREAK_DAILY_14",
                            Description = "Made a purchase 14 days in a row",
                            ImageUrl = "<svg width=\"120\" height=\"120\" viewBox=\"0 0 120 120\" xmlns=\"http://www.w3.org/2000/svg\"><circle cx=\"60\" cy=\"60\" r=\"55\" fill=\"#DDA0DD\" stroke=\"#9932CC\" stroke-width=\"3\"/><text x=\"60\" y=\"55\" font-size=\"40\" font-weight=\"bold\" text-anchor=\"middle\" fill=\"#4B0082\">🎯</text><text x=\"60\" y=\"85\" font-size=\"18\" font-weight=\"bold\" text-anchor=\"middle\" fill=\"#4B0082\">14d</text></svg>",
                            Name = "Fortnight Fanatic"
                        },
                        new
                        {
                            Id = 22,
                            Category = 2,
                            Code = "STREAK_DAILY_30",
                            Description = "Made a purchase 30 days in a row",
                            ImageUrl = "<svg width=\"120\" height=\"120\" viewBox=\"0 0 120 120\" xmlns=\"http://www.w3.org/2000/svg\"><circle cx=\"60\" cy=\"60\" r=\"55\" fill=\"#FF69B4\" stroke=\"#C71585\" stroke-width=\"3\"/><text x=\"60\" y=\"55\" font-size=\"40\" font-weight=\"bold\" text-anchor=\"middle\" fill=\"#8B008B\">💉</text><text x=\"60\" y=\"85\" font-size=\"18\" font-weight=\"bold\" text-anchor=\"middle\" fill=\"#8B008B\">30d</text></svg>",
                            Name = "Snack Addict"
                        },
                        new
                        {
                            Id = 9,
                            Category = 3,
                            Code = "COMEBACK_30",
                            Description = "First purchase after 1 month away",
                            ImageUrl = "<svg width=\"120\" height=\"120\" viewBox=\"0 0 120 120\" xmlns=\"http://www.w3.org/2000/svg\"><circle cx=\"60\" cy=\"60\" r=\"55\" fill=\"#F0E68C\" stroke=\"#BDB76B\" stroke-width=\"3\"/><text x=\"60\" y=\"55\" font-size=\"40\" font-weight=\"bold\" text-anchor=\"middle\" fill=\"#8B7355\">👋</text><text x=\"60\" y=\"85\" font-size=\"16\" font-weight=\"bold\" text-anchor=\"middle\" fill=\"#8B7355\">30d</text></svg>",
                            Name = "Long Time No See"
                        },
                        new
                        {
                            Id = 10,
                            Category = 3,
                            Code = "COMEBACK_60",
                            Description = "First purchase after 2 months away",
                            ImageUrl = "<svg width=\"120\" height=\"120\" viewBox=\"0 0 120 120\" xmlns=\"http://www.w3.org/2000/svg\"><circle cx=\"60\" cy=\"60\" r=\"55\" fill=\"#D8BFD8\" stroke=\"#9370DB\" stroke-width=\"3\"/><text x=\"60\" y=\"55\" font-size=\"40\" font-weight=\"bold\" text-anchor=\"middle\" fill=\"#4B0082\">↩️</text><text x=\"60\" y=\"85\" font-size=\"16\" font-weight=\"bold\" text-anchor=\"middle\" fill=\"#4B0082\">60d</text></svg>",
                            Name = "The Return"
                        },
                        new
                        {
                            Id = 11,
                            Category = 3,
                            Code = "COMEBACK_90",
                            Description = "First purchase after 3 months away",
                            ImageUrl = "<svg width=\"120\" height=\"120\" viewBox=\"0 0 120 120\" xmlns=\"http://www.w3.org/2000/svg\"><circle cx=\"60\" cy=\"60\" r=\"55\" fill=\"#FFE4E1\" stroke=\"#FF1493\" stroke-width=\"3\"/><text x=\"60\" y=\"55\" font-size=\"40\" font-weight=\"bold\" text-anchor=\"middle\" fill=\"#C71585\">🧟</text><text x=\"60\" y=\"85\" font-size=\"16\" font-weight=\"bold\" text-anchor=\"middle\" fill=\"#C71585\">90d</text></svg>",
                            Name = "Lazarus Rising"
                        },
                        new
                        {
                            Id = 12,
                            Category = 4,
                            Code = "IN_DEBT_15",
                            Description = "Unpaid balance of €15 or more",
                            ImageUrl = "<svg width=\"120\" height=\"120\" viewBox=\"0 0 120 120\" xmlns=\"http://www.w3.org/2000/svg\"><circle cx=\"60\" cy=\"60\" r=\"55\" fill=\"#FFE4B5\" stroke=\"#DEB887\" stroke-width=\"3\"/><text x=\"60\" y=\"50\" font-size=\"36\" font-weight=\"bold\" text-anchor=\"middle\" fill=\"#8B4513\">📝</text><text x=\"60\" y=\"85\" font-size=\"20\" font-weight=\"bold\" text-anchor=\"middle\" fill=\"#8B4513\">€15</text></svg>",
                            Name = "Tab Starter"
                        },
                        new
                        {
                            Id = 13,
                            Category = 4,
                            Code = "IN_DEBT_20",
                            Description = "Unpaid balance of €20 or more",
                            ImageUrl = "<svg width=\"120\" height=\"120\" viewBox=\"0 0 120 120\" xmlns=\"http://www.w3.org/2000/svg\"><circle cx=\"60\" cy=\"60\" r=\"55\" fill=\"#FFDAB9\" stroke=\"#CD853F\" stroke-width=\"3\"/><text x=\"60\" y=\"50\" font-size=\"36\" font-weight=\"bold\" text-anchor=\"middle\" fill=\"#8B4513\">💳</text><text x=\"60\" y=\"85\" font-size=\"20\" font-weight=\"bold\" text-anchor=\"middle\" fill=\"#8B4513\">€20</text></svg>",
                            Name = "Credit Curious"
                        },
                        new
                        {
                            Id = 14,
                            Category = 4,
                            Code = "IN_DEBT_25",
                            Description = "Unpaid balance of €25 or more",
                            ImageUrl = "<svg width=\"120\" height=\"120\" viewBox=\"0 0 120 120\" xmlns=\"http://www.w3.org/2000/svg\"><circle cx=\"60\" cy=\"60\" r=\"55\" fill=\"#FFB6C1\" stroke=\"#FF69B4\" stroke-width=\"3\"/><text x=\"60\" y=\"50\" font-size=\"36\" font-weight=\"bold\" text-anchor=\"middle\" fill=\"#C71585\">💸</text><text x=\"60\" y=\"85\" font-size=\"20\" font-weight=\"bold\" text-anchor=\"middle\" fill=\"#C71585\">€25</text></svg>",
                            Name = "Living on Credit"
                        },
                        new
                        {
                            Id = 23,
                            Category = 4,
                            Code = "IN_DEBT_30",
                            Description = "Unpaid balance of €30 or more",
                            ImageUrl = "<svg width=\"120\" height=\"120\" viewBox=\"0 0 120 120\" xmlns=\"http://www.w3.org/2000/svg\"><circle cx=\"60\" cy=\"60\" r=\"55\" fill=\"#FFA07A\" stroke=\"#FF6347\" stroke-width=\"3\"/><text x=\"60\" y=\"50\" font-size=\"36\" font-weight=\"bold\" text-anchor=\"middle\" fill=\"#8B0000\">📞</text><text x=\"60\" y=\"85\" font-size=\"20\" font-weight=\"bold\" text-anchor=\"middle\" fill=\"#8B0000\">€30</text></svg>",
                            Name = "Debt Collector's Friend"
                        },
                        new
                        {
                            Id = 24,
                            Category = 4,
                            Code = "IN_DEBT_35",
                            Description = "Unpaid balance of €35 or more",
                            ImageUrl = "<svg width=\"120\" height=\"120\" viewBox=\"0 0 120 120\" xmlns=\"http://www.w3.org/2000/svg\"><circle cx=\"60\" cy=\"60\" r=\"55\" fill=\"#FF6B6B\" stroke=\"#DC143C\" stroke-width=\"3\"/><text x=\"60\" y=\"50\" font-size=\"32\" font-weight=\"bold\" text-anchor=\"middle\" fill=\"#8B0000\">🚫💰</text><text x=\"60\" y=\"85\" font-size=\"20\" font-weight=\"bold\" text-anchor=\"middle\" fill=\"#8B0000\">€35</text></svg>",
                            Name = "Financial Freedom? Never Heard of It"
                        },
                        new
                        {
                            Id = 15,
                            Category = 5,
                            Code = "TOTAL_SPENT_100",
                            Description = "Spent €100 or more in total",
                            ImageUrl = "<svg width=\"120\" height=\"120\" viewBox=\"0 0 120 120\" xmlns=\"http://www.w3.org/2000/svg\"><circle cx=\"60\" cy=\"60\" r=\"55\" fill=\"#FFD700\" stroke=\"#FFA500\" stroke-width=\"3\"/><text x=\"60\" y=\"50\" font-size=\"36\" font-weight=\"bold\" text-anchor=\"middle\" fill=\"#B8860B\">💯</text><text x=\"60\" y=\"85\" font-size=\"18\" font-weight=\"bold\" text-anchor=\"middle\" fill=\"#B8860B\">€100</text></svg>",
                            Name = "Century Club"
                        },
                        new
                        {
                            Id = 16,
                            Category = 5,
                            Code = "TOTAL_SPENT_150",
                            Description = "Spent €150 or more in total",
                            ImageUrl = "<svg width=\"120\" height=\"120\" viewBox=\"0 0 120 120\" xmlns=\"http://www.w3.org/2000/svg\"><circle cx=\"60\" cy=\"60\" r=\"55\" fill=\"#E6E6FA\" stroke=\"#9370DB\" stroke-width=\"3\"/><text x=\"60\" y=\"50\" font-size=\"36\" font-weight=\"bold\" text-anchor=\"middle\" fill=\"#4B0082\">🍷</text><text x=\"60\" y=\"85\" font-size=\"18\" font-weight=\"bold\" text-anchor=\"middle\" fill=\"#4B0082\">€150</text></svg>",
                            Name = "Snack Connoisseur"
                        },
                        new
                        {
                            Id = 17,
                            Category = 5,
                            Code = "TOTAL_SPENT_200",
                            Description = "Spent €200 or more in total",
                            ImageUrl = "<svg width=\"120\" height=\"120\" viewBox=\"0 0 120 120\" xmlns=\"http://www.w3.org/2000/svg\"><circle cx=\"60\" cy=\"60\" r=\"55\" fill=\"#87CEEB\" stroke=\"#4169E1\" stroke-width=\"3\"/><text x=\"60\" y=\"50\" font-size=\"36\" font-weight=\"bold\" text-anchor=\"middle\" fill=\"#00008B\">🏆</text><text x=\"60\" y=\"85\" font-size=\"18\" font-weight=\"bold\" text-anchor=\"middle\" fill=\"#00008B\">€200</text></svg>",
                            Name = "Snackbox Legend"
                        },
                        new
                        {
                            Id = 25,
                            Category = 5,
                            Code = "TOTAL_SPENT_50",
                            Description = "Spent €50 or more in total",
                            ImageUrl = "<svg width=\"120\" height=\"120\" viewBox=\"0 0 120 120\" xmlns=\"http://www.w3.org/2000/svg\"><circle cx=\"60\" cy=\"60\" r=\"55\" fill=\"#C0C0C0\" stroke=\"#A9A9A9\" stroke-width=\"3\"/><text x=\"60\" y=\"50\" font-size=\"36\" font-weight=\"bold\" text-anchor=\"middle\" fill=\"#696969\">🥈</text><text x=\"60\" y=\"85\" font-size=\"20\" font-weight=\"bold\" text-anchor=\"middle\" fill=\"#696969\">€50</text></svg>",
                            Name = "First Fifty"
                        },
                        new
                        {
                            Id = 26,
                            Category = 5,
                            Code = "TOTAL_SPENT_300",
                            Description = "Spent €300 or more in total",
                            ImageUrl = "<svg width=\"120\" height=\"120\" viewBox=\"0 0 120 120\" xmlns=\"http://www.w3.org/2000/svg\"><circle cx=\"60\" cy=\"60\" r=\"55\" fill=\"#DDA0DD\" stroke=\"#BA55D3\" stroke-width=\"3\"/><text x=\"60\" y=\"50\" font-size=\"36\" font-weight=\"bold\" text-anchor=\"middle\" fill=\"#8B008B\">👑</text><text x=\"60\" y=\"85\" font-size=\"18\" font-weight=\"bold\" text-anchor=\"middle\" fill=\"#8B008B\">€300</text></svg>",
                            Name = "Snack Royalty"
                        },
                        new
                        {
                            Id = 27,
                            Category = 5,
                            Code = "TOTAL_SPENT_500",
                            Description = "Spent €500 or more in total",
                            ImageUrl = "<svg width=\"120\" height=\"120\" viewBox=\"0 0 120 120\" xmlns=\"http://www.w3.org/2000/svg\"><circle cx=\"60\" cy=\"60\" r=\"55\" fill=\"#FF69B4\" stroke=\"#FF1493\" stroke-width=\"3\"/><path d=\"M 60 20 L 70 45 L 95 45 L 75 60 L 85 85 L 60 70 L 35 85 L 45 60 L 25 45 L 50 45 Z\" fill=\"#FFD700\" stroke=\"#FFA500\" stroke-width=\"2\"/><text x=\"60\" y=\"65\" font-size=\"16\" font-weight=\"bold\" text-anchor=\"middle\" fill=\"#8B0000\">€500</text></svg>",
                            Name = "Snack God"
                        },
                        new
                        {
                            Id = 28,
                            Category = 6,
                            Code = "EARLY_BIRD",
                            Description = "Made a purchase before 8 AM",
                            ImageUrl = "<svg width=\"120\" height=\"120\" viewBox=\"0 0 120 120\" xmlns=\"http://www.w3.org/2000/svg\"><circle cx=\"60\" cy=\"60\" r=\"55\" fill=\"#87CEEB\" stroke=\"#4682B4\" stroke-width=\"3\"/><text x=\"60\" y=\"55\" font-size=\"40\" font-weight=\"bold\" text-anchor=\"middle\" fill=\"#191970\">🐦</text><text x=\"60\" y=\"85\" font-size=\"16\" font-weight=\"bold\" text-anchor=\"middle\" fill=\"#191970\">&lt;8AM</text></svg>",
                            Name = "Early Bird"
                        },
                        new
                        {
                            Id = 29,
                            Category = 6,
                            Code = "NIGHT_OWL",
                            Description = "Made a purchase after 8 PM",
                            ImageUrl = "<svg width=\"120\" height=\"120\" viewBox=\"0 0 120 120\" xmlns=\"http://www.w3.org/2000/svg\"><circle cx=\"60\" cy=\"60\" r=\"55\" fill=\"#191970\" stroke=\"#000080\" stroke-width=\"3\"/><text x=\"60\" y=\"55\" font-size=\"40\" font-weight=\"bold\" text-anchor=\"middle\" fill=\"#FFD700\">🦉</text><text x=\"60\" y=\"85\" font-size=\"16\" font-weight=\"bold\" text-anchor=\"middle\" fill=\"#FFD700\">&gt;8PM</text></svg>",
                            Name = "Night Owl"
                        },
                        new
                        {
                            Id = 30,
                            Category = 6,
                            Code = "LUNCH_RUSH",
                            Description = "Made a purchase between 12-1 PM",
                            ImageUrl = "<svg width=\"120\" height=\"120\" viewBox=\"0 0 120 120\" xmlns=\"http://www.w3.org/2000/svg\"><circle cx=\"60\" cy=\"60\" r=\"55\" fill=\"#FFE4B5\" stroke=\"#D2691E\" stroke-width=\"3\"/><text x=\"60\" y=\"55\" font-size=\"40\" font-weight=\"bold\" text-anchor=\"middle\" fill=\"#8B4513\">🍱</text><text x=\"60\" y=\"85\" font-size=\"16\" font-weight=\"bold\" text-anchor=\"middle\" fill=\"#8B4513\">12-1PM</text></svg>",
                            Name = "Lunch Rush Survivor"
                        },
                        new
                        {
                            Id = 31,
                            Category = 6,
                            Code = "WEEKEND_WARRIOR",
                            Description = "Made a purchase on a Saturday or Sunday",
                            ImageUrl = "<svg width=\"120\" height=\"120\" viewBox=\"0 0 120 120\" xmlns=\"http://www.w3.org/2000/svg\"><circle cx=\"60\" cy=\"60\" r=\"55\" fill=\"#98FB98\" stroke=\"#228B22\" stroke-width=\"3\"/><text x=\"60\" y=\"55\" font-size=\"40\" font-weight=\"bold\" text-anchor=\"middle\" fill=\"#006400\">🎉</text><text x=\"60\" y=\"85\" font-size=\"14\" font-weight=\"bold\" text-anchor=\"middle\" fill=\"#006400\">Sat/Sun</text></svg>",
                            Name = "Weekend Warrior"
                        },
                        new
                        {
                            Id = 32,
                            Category = 6,
                            Code = "MONDAY_BLUES",
                            Description = "Made a purchase on a Monday",
                            ImageUrl = "<svg width=\"120\" height=\"120\" viewBox=\"0 0 120 120\" xmlns=\"http://www.w3.org/2000/svg\"><circle cx=\"60\" cy=\"60\" r=\"55\" fill=\"#ADD8E6\" stroke=\"#4682B4\" stroke-width=\"3\"/><text x=\"60\" y=\"55\" font-size=\"40\" font-weight=\"bold\" text-anchor=\"middle\" fill=\"#000080\">😔</text><text x=\"60\" y=\"85\" font-size=\"16\" font-weight=\"bold\" text-anchor=\"middle\" fill=\"#000080\">Monday</text></svg>",
                            Name = "Monday Blues Cure"
                        },
                        new
                        {
                            Id = 33,
                            Category = 6,
                            Code = "FRIDAY_TREAT",
                            Description = "Made a purchase on a Friday",
                            ImageUrl = "<svg width=\"120\" height=\"120\" viewBox=\"0 0 120 120\" xmlns=\"http://www.w3.org/2000/svg\"><circle cx=\"60\" cy=\"60\" r=\"55\" fill=\"#FFD700\" stroke=\"#FFA500\" stroke-width=\"3\"/><text x=\"60\" y=\"55\" font-size=\"40\" font-weight=\"bold\" text-anchor=\"middle\" fill=\"#8B4513\">🎊</text><text x=\"60\" y=\"85\" font-size=\"16\" font-weight=\"bold\" text-anchor=\"middle\" fill=\"#8B4513\">Friday</text></svg>",
                            Name = "Friday Treat Yourself"
                        },
                        new
                        {
                            Id = 34,
                            Category = 7,
                            Code = "FIRST_PURCHASE",
                            Description = "Made your first purchase",
                            ImageUrl = "<svg width=\"120\" height=\"120\" viewBox=\"0 0 120 120\" xmlns=\"http://www.w3.org/2000/svg\"><circle cx=\"60\" cy=\"60\" r=\"55\" fill=\"#FFE4E1\" stroke=\"#FF69B4\" stroke-width=\"3\"/><text x=\"60\" y=\"55\" font-size=\"40\" font-weight=\"bold\" text-anchor=\"middle\" fill=\"#C71585\">🎈</text><text x=\"60\" y=\"85\" font-size=\"20\" font-weight=\"bold\" text-anchor=\"middle\" fill=\"#C71585\">1st</text></svg>",
                            Name = "Welcome to the Club!"
                        },
                        new
                        {
                            Id = 35,
                            Category = 7,
                            Code = "PURCHASE_10",
                            Description = "Made 10 purchases total",
                            ImageUrl = "<svg width=\"120\" height=\"120\" viewBox=\"0 0 120 120\" xmlns=\"http://www.w3.org/2000/svg\"><circle cx=\"60\" cy=\"60\" r=\"55\" fill=\"#F0E68C\" stroke=\"#DAA520\" stroke-width=\"3\"/><text x=\"60\" y=\"55\" font-size=\"40\" font-weight=\"bold\" text-anchor=\"middle\" fill=\"#8B4513\">🎫</text><text x=\"60\" y=\"85\" font-size=\"20\" font-weight=\"bold\" text-anchor=\"middle\" fill=\"#8B4513\">10</text></svg>",
                            Name = "Regular Customer"
                        },
                        new
                        {
                            Id = 36,
                            Category = 7,
                            Code = "PURCHASE_50",
                            Description = "Made 50 purchases total",
                            ImageUrl = "<svg width=\"120\" height=\"120\" viewBox=\"0 0 120 120\" xmlns=\"http://www.w3.org/2000/svg\"><circle cx=\"60\" cy=\"60\" r=\"55\" fill=\"#C0C0C0\" stroke=\"#A9A9A9\" stroke-width=\"3\"/><text x=\"60\" y=\"55\" font-size=\"40\" font-weight=\"bold\" text-anchor=\"middle\" fill=\"#696969\">🎖️</text><text x=\"60\" y=\"85\" font-size=\"20\" font-weight=\"bold\" text-anchor=\"middle\" fill=\"#696969\">50</text></svg>",
                            Name = "Snack Veteran"
                        },
                        new
                        {
                            Id = 37,
                            Category = 7,
                            Code = "PURCHASE_100",
                            Description = "Made 100 purchases total",
                            ImageUrl = "<svg width=\"120\" height=\"120\" viewBox=\"0 0 120 120\" xmlns=\"http://www.w3.org/2000/svg\"><circle cx=\"60\" cy=\"60\" r=\"55\" fill=\"#FFD700\" stroke=\"#FFA500\" stroke-width=\"3\"/><text x=\"60\" y=\"55\" font-size=\"40\" font-weight=\"bold\" text-anchor=\"middle\" fill=\"#B8860B\">🎖️</text><text x=\"60\" y=\"85\" font-size=\"18\" font-weight=\"bold\" text-anchor=\"middle\" fill=\"#B8860B\">100</text></svg>",
                            Name = "Snack Centurion"
                        },
                        new
                        {
                            Id = 38,
                            Category = 7,
                            Code = "PURCHASE_250",
                            Description = "Made 250 purchases total",
                            ImageUrl = "<svg width=\"120\" height=\"120\" viewBox=\"0 0 120 120\" xmlns=\"http://www.w3.org/2000/svg\"><circle cx=\"60\" cy=\"60\" r=\"55\" fill=\"#DDA0DD\" stroke=\"#BA55D3\" stroke-width=\"3\"/><text x=\"60\" y=\"55\" font-size=\"40\" font-weight=\"bold\" text-anchor=\"middle\" fill=\"#8B008B\">🥋</text><text x=\"60\" y=\"85\" font-size=\"18\" font-weight=\"bold\" text-anchor=\"middle\" fill=\"#8B008B\">250</text></svg>",
                            Name = "Snack Master"
                        },
                        new
                        {
                            Id = 39,
                            Category = 7,
                            Code = "PURCHASE_500",
                            Description = "Made 500 purchases total",
                            ImageUrl = "<svg width=\"120\" height=\"120\" viewBox=\"0 0 120 120\" xmlns=\"http://www.w3.org/2000/svg\"><circle cx=\"60\" cy=\"60\" r=\"55\" fill=\"#FF4500\" stroke=\"#8B0000\" stroke-width=\"3\"/><text x=\"60\" y=\"55\" font-size=\"40\" font-weight=\"bold\" text-anchor=\"middle\" fill=\"#FFD700\">👑</text><text x=\"60\" y=\"85\" font-size=\"18\" font-weight=\"bold\" text-anchor=\"middle\" fill=\"#FFD700\">500</text></svg>",
                            Name = "Snack Overlord"
                        },
                        new
                        {
                            Id = 40,
                            Category = 8,
                            Code = "SPEED_DEMON",
                            Description = "Made 2 purchases within 1 minute",
                            ImageUrl = "<svg width=\"120\" height=\"120\" viewBox=\"0 0 120 120\" xmlns=\"http://www.w3.org/2000/svg\"><circle cx=\"60\" cy=\"60\" r=\"55\" fill=\"#FF6347\" stroke=\"#DC143C\" stroke-width=\"3\"/><text x=\"60\" y=\"55\" font-size=\"40\" font-weight=\"bold\" text-anchor=\"middle\" fill=\"#8B0000\">⚡</text><text x=\"60\" y=\"85\" font-size=\"14\" font-weight=\"bold\" text-anchor=\"middle\" fill=\"#8B0000\">&lt;1min</text></svg>",
                            Name = "Speed Demon"
                        },
                        new
                        {
                            Id = 41,
                            Category = 8,
                            Code = "DOUBLE_TROUBLE",
                            Description = "Made exactly 2 purchases in a session",
                            ImageUrl = "<svg width=\"120\" height=\"120\" viewBox=\"0 0 120 120\" xmlns=\"http://www.w3.org/2000/svg\"><circle cx=\"60\" cy=\"60\" r=\"55\" fill=\"#FFB6C1\" stroke=\"#FF69B4\" stroke-width=\"3\"/><text x=\"60\" y=\"65\" font-size=\"50\" font-weight=\"bold\" text-anchor=\"middle\" fill=\"#C71585\">2️⃣</text></svg>",
                            Name = "Double Trouble"
                        },
                        new
                        {
                            Id = 42,
                            Category = 8,
                            Code = "TRIPLE_THREAT",
                            Description = "Made exactly 3 purchases in a session",
                            ImageUrl = "<svg width=\"120\" height=\"120\" viewBox=\"0 0 120 120\" xmlns=\"http://www.w3.org/2000/svg\"><circle cx=\"60\" cy=\"60\" r=\"55\" fill=\"#DDA0DD\" stroke=\"#BA55D3\" stroke-width=\"3\"/><text x=\"60\" y=\"65\" font-size=\"50\" font-weight=\"bold\" text-anchor=\"middle\" fill=\"#8B008B\">3️⃣</text></svg>",
                            Name = "Triple Threat"
                        },
                        new
                        {
                            Id = 43,
                            Category = 8,
                            Code = "LUCKY_SEVEN",
                            Description = "Made exactly 7 purchases in a session",
                            ImageUrl = "<svg width=\"120\" height=\"120\" viewBox=\"0 0 120 120\" xmlns=\"http://www.w3.org/2000/svg\"><circle cx=\"60\" cy=\"60\" r=\"55\" fill=\"#32CD32\" stroke=\"#228B22\" stroke-width=\"3\"/><text x=\"60\" y=\"65\" font-size=\"50\" font-weight=\"bold\" text-anchor=\"middle\" fill=\"#006400\">7️⃣</text></svg>",
                            Name = "Lucky Seven"
                        },
                        new
                        {
                            Id = 44,
                            Category = 8,
                            Code = "ROUND_NUMBER",
                            Description = "Made a purchase totaling exactly €5 or €10",
                            ImageUrl = "<svg width=\"120\" height=\"120\" viewBox=\"0 0 120 120\" xmlns=\"http://www.w3.org/2000/svg\"><circle cx=\"60\" cy=\"60\" r=\"55\" fill=\"#E0FFFF\" stroke=\"#00CED1\" stroke-width=\"3\"/><text x=\"60\" y=\"55\" font-size=\"40\" font-weight=\"bold\" text-anchor=\"middle\" fill=\"#008B8B\">✔️</text><text x=\"60\" y=\"85\" font-size=\"16\" font-weight=\"bold\" text-anchor=\"middle\" fill=\"#008B8B\">€5/€10</text></svg>",
                            Name = "OCD Approved"
                        },
                        new
                        {
                            Id = 45,
                            Category = 8,
                            Code = "SAME_AGAIN",
                            Description = "Made 3 identical purchases in a row",
                            ImageUrl = "<svg width=\"120\" height=\"120\" viewBox=\"0 0 120 120\" xmlns=\"http://www.w3.org/2000/svg\"><circle cx=\"60\" cy=\"60\" r=\"55\" fill=\"#FAFAD2\" stroke=\"#BDB76B\" stroke-width=\"3\"/><text x=\"60\" y=\"55\" font-size=\"40\" font-weight=\"bold\" text-anchor=\"middle\" fill=\"#8B7355\">🔁</text><text x=\"60\" y=\"85\" font-size=\"16\" font-weight=\"bold\" text-anchor=\"middle\" fill=\"#8B7355\">x3</text></svg>",
                            Name = "Same Again, Please"
                        },
                        new
                        {
                            Id = 46,
                            Category = 8,
                            Code = "PAID_UP",
                            Description = "Paid off your entire balance",
                            ImageUrl = "<svg width=\"120\" height=\"120\" viewBox=\"0 0 120 120\" xmlns=\"http://www.w3.org/2000/svg\"><circle cx=\"60\" cy=\"60\" r=\"55\" fill=\"#90EE90\" stroke=\"#32CD32\" stroke-width=\"3\"/><text x=\"60\" y=\"55\" font-size=\"40\" font-weight=\"bold\" text-anchor=\"middle\" fill=\"#006400\">✅</text><text x=\"60\" y=\"85\" font-size=\"16\" font-weight=\"bold\" text-anchor=\"middle\" fill=\"#006400\">€0</text></svg>",
                            Name = "Debt Free!"
                        },
                        new
                        {
                            Id = 47,
                            Category = 8,
                            Code = "GENEROUS_SOUL",
                            Description = "Have a positive balance (credit) of €10 or more",
                            ImageUrl = "<svg width=\"120\" height=\"120\" viewBox=\"0 0 120 120\" xmlns=\"http://www.w3.org/2000/svg\"><circle cx=\"60\" cy=\"60\" r=\"55\" fill=\"#FFD700\" stroke=\"#FFA500\" stroke-width=\"3\"/><text x=\"60\" y=\"55\" font-size=\"40\" font-weight=\"bold\" text-anchor=\"middle\" fill=\"#B8860B\">💝</text><text x=\"60\" y=\"85\" font-size=\"16\" font-weight=\"bold\" text-anchor=\"middle\" fill=\"#B8860B\">+€10</text></svg>",
                            Name = "Generous Soul"
                        },
                        new
                        {
                            Id = 48,
                            Category = 8,
                            Code = "SNACK_BIRTHDAY",
                            Description = "Made a purchase exactly 1 year after your first",
                            ImageUrl = "<svg width=\"120\" height=\"120\" viewBox=\"0 0 120 120\" xmlns=\"http://www.w3.org/2000/svg\"><circle cx=\"60\" cy=\"60\" r=\"55\" fill=\"#FFB6C1\" stroke=\"#FF1493\" stroke-width=\"3\"/><text x=\"60\" y=\"55\" font-size=\"40\" font-weight=\"bold\" text-anchor=\"middle\" fill=\"#C71585\">🎂</text><text x=\"60\" y=\"85\" font-size=\"14\" font-weight=\"bold\" text-anchor=\"middle\" fill=\"#C71585\">1 year</text></svg>",
                            Name = "Happy Snack-iversary!"
                        },
                        new
                        {
                            Id = 49,
                            Category = 8,
                            Code = "THIRTEENTH",
                            Description = "Made a purchase totaling exactly €13",
                            ImageUrl = "<svg width=\"120\" height=\"120\" viewBox=\"0 0 120 120\" xmlns=\"http://www.w3.org/2000/svg\"><circle cx=\"60\" cy=\"60\" r=\"55\" fill=\"#2F4F4F\" stroke=\"#000000\" stroke-width=\"3\"/><text x=\"60\" y=\"55\" font-size=\"40\" font-weight=\"bold\" text-anchor=\"middle\" fill=\"#FFD700\">🖤</text><text x=\"60\" y=\"85\" font-size=\"20\" font-weight=\"bold\" text-anchor=\"middle\" fill=\"#FFD700\">€13</text></svg>",
                            Name = "Unlucky 13"
                        },
                        new
                        {
                            Id = 50,
                            Category = 8,
                            Code = "NICE",
                            Description = "Made a purchase totaling exactly €6.90",
                            ImageUrl = "<svg width=\"120\" height=\"120\" viewBox=\"0 0 120 120\" xmlns=\"http://www.w3.org/2000/svg\"><circle cx=\"60\" cy=\"60\" r=\"55\" fill=\"#FF69B4\" stroke=\"#FF1493\" stroke-width=\"3\"/><text x=\"60\" y=\"55\" font-size=\"40\" font-weight=\"bold\" text-anchor=\"middle\" fill=\"#8B008B\">😏</text><text x=\"60\" y=\"85\" font-size=\"16\" font-weight=\"bold\" text-anchor=\"middle\" fill=\"#8B008B\">€6.90</text></svg>",
                            Name = "Nice."
                        });
                });

            modelBuilder.Entity("Snackbox.Api.Models.Barcode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("amount");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsLoginOnly")
                        .HasColumnType("boolean")
                        .HasColumnName("is_login_only");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("barcodes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 5.00m,
                            Code = "4061461764012",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsLoginOnly = false,
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            Amount = 10.00m,
                            Code = "USER2-10EUR",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsLoginOnly = false,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            Amount = 5.00m,
                            Code = "USER3-5EUR",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsLoginOnly = false,
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            Amount = 10.00m,
                            Code = "USER3-10EUR",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsLoginOnly = false,
                            UserId = 3
                        },
                        new
                        {
                            Id = 5,
                            Amount = 0m,
                            Code = "4260473313809",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsLoginOnly = true,
                            UserId = 1
                        },
                        new
                        {
                            Id = 6,
                            Amount = 0m,
                            Code = "USER2-LOGIN",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsLoginOnly = true,
                            UserId = 2
                        },
                        new
                        {
                            Id = 7,
                            Amount = 0m,
                            Code = "USER3-LOGIN",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsLoginOnly = true,
                            UserId = 3
                        });
                });

            modelBuilder.Entity("Snackbox.Api.Models.BarcodeScan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("amount");

                    b.Property<int>("BarcodeId")
                        .HasColumnType("integer")
                        .HasColumnName("barcode_id");

                    b.Property<int>("PurchaseId")
                        .HasColumnType("integer")
                        .HasColumnName("purchase_id");

                    b.Property<DateTime>("ScannedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scanned_at");

                    b.HasKey("Id");

                    b.HasIndex("BarcodeId");

                    b.HasIndex("PurchaseId");

                    b.ToTable("barcode_scans");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 5.00m,
                            BarcodeId = 1,
                            PurchaseId = 1,
                            ScannedAt = new DateTime(2024, 1, 6, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            Amount = 10.00m,
                            BarcodeId = 2,
                            PurchaseId = 1,
                            ScannedAt = new DateTime(2024, 1, 6, 0, 2, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            Amount = 5.00m,
                            BarcodeId = 3,
                            PurchaseId = 2,
                            ScannedAt = new DateTime(2024, 1, 11, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Snackbox.Api.Models.CashRegister", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CurrentBalance")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("current_balance");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated_at");

                    b.Property<int>("LastUpdatedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("last_updated_by_user_id");

                    b.HasKey("Id");

                    b.HasIndex("LastUpdatedByUserId");

                    b.ToTable("cash_register");
                });

            modelBuilder.Entity("Snackbox.Api.Models.Deposit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("amount");

                    b.Property<DateTime>("DepositedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deposited_at");

                    b.Property<int?>("LinkedPaymentId")
                        .HasColumnType("integer")
                        .HasColumnName("linked_payment_id");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("deposits");
                });

            modelBuilder.Entity("Snackbox.Api.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AdminUserId")
                        .HasColumnType("integer")
                        .HasColumnName("admin_user_id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("amount");

                    b.Property<int?>("LinkedDepositId")
                        .HasColumnType("integer")
                        .HasColumnName("linked_deposit_id");

                    b.Property<int?>("LinkedWithdrawalId")
                        .HasColumnType("integer")
                        .HasColumnName("linked_withdrawal_id");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<DateTime>("PaidAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paid_at");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("AdminUserId");

                    b.HasIndex("LinkedDepositId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("payments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 20.00m,
                            Notes = "Initial payment",
                            PaidAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Type = 0,
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            Amount = 15.00m,
                            Notes = "Cash payment",
                            PaidAt = new DateTime(2024, 1, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Type = 0,
                            UserId = 3
                        });
                });

            modelBuilder.Entity("Snackbox.Api.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("BestBeforeInStock")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("best_before_in_stock");

                    b.Property<DateTime?>("BestBeforeOnShelf")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("best_before_on_shelf");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Chips - Salt"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Chocolate Bar"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Energy Drink"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Cookies"
                        });
                });

            modelBuilder.Entity("Snackbox.Api.Models.ProductBarcode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("barcode");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.HasKey("Id");

                    b.HasIndex("Barcode")
                        .IsUnique();

                    b.HasIndex("ProductId");

                    b.ToTable("product_barcodes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Barcode = "1234567890123",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = 1,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 2,
                            Barcode = "1234567890123-BOX",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = 1,
                            Quantity = 12
                        },
                        new
                        {
                            Id = 3,
                            Barcode = "1234567890124",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = 2,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 4,
                            Barcode = "1234567890124-PACK",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = 2,
                            Quantity = 5
                        },
                        new
                        {
                            Id = 5,
                            Barcode = "1234567890125",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = 3,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 6,
                            Barcode = "1234567890126",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = 4,
                            Quantity = 1
                        });
                });

            modelBuilder.Entity("Snackbox.Api.Models.ProductBatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BestBeforeDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("best_before_date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("product_batches");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BestBeforeDate = new DateTime(2025, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = 1
                        },
                        new
                        {
                            Id = 2,
                            BestBeforeDate = new DateTime(2025, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = 2
                        },
                        new
                        {
                            Id = 3,
                            BestBeforeDate = new DateTime(2025, 12, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = 3
                        },
                        new
                        {
                            Id = 4,
                            BestBeforeDate = new DateTime(2025, 5, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = 4
                        });
                });

            modelBuilder.Entity("Snackbox.Api.Models.Purchase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal?>("ManualAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("manual_amount");

                    b.Property<int?>("ReferencePurchaseId")
                        .HasColumnType("integer")
                        .HasColumnName("reference_purchase_id");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ReferencePurchaseId");

                    b.HasIndex("UserId");

                    b.ToTable("purchases");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompletedAt = new DateTime(2024, 1, 6, 0, 5, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2024, 1, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            Type = 0,
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            CompletedAt = new DateTime(2024, 1, 11, 0, 3, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2024, 1, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Type = 0,
                            UserId = 3
                        });
                });

            modelBuilder.Entity("Snackbox.Api.Models.ShelvingAction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ActionAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("action_at");

                    b.Property<int>("ProductBatchId")
                        .HasColumnType("integer")
                        .HasColumnName("product_batch_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("ProductBatchId");

                    b.ToTable("shelving_actions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActionAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProductBatchId = 1,
                            Quantity = 50,
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            ActionAt = new DateTime(2024, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProductBatchId = 1,
                            Quantity = 20,
                            Type = 2
                        },
                        new
                        {
                            Id = 3,
                            ActionAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProductBatchId = 2,
                            Quantity = 30,
                            Type = 0
                        },
                        new
                        {
                            Id = 4,
                            ActionAt = new DateTime(2024, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProductBatchId = 2,
                            Quantity = 15,
                            Type = 2
                        },
                        new
                        {
                            Id = 5,
                            ActionAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProductBatchId = 3,
                            Quantity = 40,
                            Type = 0
                        },
                        new
                        {
                            Id = 6,
                            ActionAt = new DateTime(2024, 1, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProductBatchId = 3,
                            Quantity = 25,
                            Type = 2
                        },
                        new
                        {
                            Id = 7,
                            ActionAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProductBatchId = 4,
                            Quantity = 35,
                            Type = 0
                        },
                        new
                        {
                            Id = 8,
                            ActionAt = new DateTime(2024, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProductBatchId = 4,
                            Quantity = 18,
                            Type = 2
                        });
                });

            modelBuilder.Entity("Snackbox.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean")
                        .HasColumnName("is_admin");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@snackbox.com",
                            IsAdmin = true,
                            PasswordHash = "$2a$11$7EW8wLqhqKQZH8J6rX5kQ.gBAGZERO3WEhOw84rLKyWNOe90gtIZi",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "john.doe@company.com",
                            IsAdmin = false,
                            PasswordHash = "$2a$11$7EW8wLqhqKQZH8J6rX5kQ.nhwgnkeU3Z3ua5zEq5X5I6iMvqFFYkO",
                            Username = "john.doe"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "jane.smith@company.com",
                            IsAdmin = false,
                            Username = "jane.smith"
                        });
                });

            modelBuilder.Entity("Snackbox.Api.Models.UserAchievement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AchievementId")
                        .HasColumnType("integer")
                        .HasColumnName("achievement_id");

                    b.Property<decimal?>("DebtAtEarning")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("debt_at_earning");

                    b.Property<DateTime>("EarnedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("earned_at");

                    b.Property<bool>("HasBeenShown")
                        .HasColumnType("boolean")
                        .HasColumnName("has_been_shown");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("AchievementId");

                    b.HasIndex("UserId", "AchievementId", "EarnedAt");

                    b.ToTable("user_achievements");
                });

            modelBuilder.Entity("Snackbox.Api.Models.Withdrawal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("amount");

                    b.Property<int?>("LinkedPaymentId")
                        .HasColumnType("integer")
                        .HasColumnName("linked_payment_id");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("WithdrawnAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("withdrawn_at");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("withdrawals");
                });

            modelBuilder.Entity("Snackbox.Api.Models.Barcode", b =>
                {
                    b.HasOne("Snackbox.Api.Models.User", "User")
                        .WithMany("Barcodes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Snackbox.Api.Models.BarcodeScan", b =>
                {
                    b.HasOne("Snackbox.Api.Models.Barcode", "Barcode")
                        .WithMany("Scans")
                        .HasForeignKey("BarcodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Snackbox.Api.Models.Purchase", "Purchase")
                        .WithMany("Scans")
                        .HasForeignKey("PurchaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Barcode");

                    b.Navigation("Purchase");
                });

            modelBuilder.Entity("Snackbox.Api.Models.CashRegister", b =>
                {
                    b.HasOne("Snackbox.Api.Models.User", "LastUpdatedByUser")
                        .WithMany()
                        .HasForeignKey("LastUpdatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LastUpdatedByUser");
                });

            modelBuilder.Entity("Snackbox.Api.Models.Deposit", b =>
                {
                    b.HasOne("Snackbox.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Snackbox.Api.Models.Payment", b =>
                {
                    b.HasOne("Snackbox.Api.Models.User", "AdminUser")
                        .WithMany()
                        .HasForeignKey("AdminUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Snackbox.Api.Models.Deposit", "LinkedDeposit")
                        .WithOne("LinkedPayment")
                        .HasForeignKey("Snackbox.Api.Models.Payment", "LinkedDepositId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Snackbox.Api.Models.User", "User")
                        .WithMany("Payments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdminUser");

                    b.Navigation("LinkedDeposit");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Snackbox.Api.Models.ProductBarcode", b =>
                {
                    b.HasOne("Snackbox.Api.Models.Product", "Product")
                        .WithMany("Barcodes")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Snackbox.Api.Models.ProductBatch", b =>
                {
                    b.HasOne("Snackbox.Api.Models.Product", "Product")
                        .WithMany("Batches")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Snackbox.Api.Models.Purchase", b =>
                {
                    b.HasOne("Snackbox.Api.Models.Purchase", "ReferencePurchase")
                        .WithMany()
                        .HasForeignKey("ReferencePurchaseId");

                    b.HasOne("Snackbox.Api.Models.User", "User")
                        .WithMany("Purchases")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReferencePurchase");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Snackbox.Api.Models.ShelvingAction", b =>
                {
                    b.HasOne("Snackbox.Api.Models.ProductBatch", "ProductBatch")
                        .WithMany("ShelvingActions")
                        .HasForeignKey("ProductBatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductBatch");
                });

            modelBuilder.Entity("Snackbox.Api.Models.UserAchievement", b =>
                {
                    b.HasOne("Snackbox.Api.Models.Achievement", "Achievement")
                        .WithMany("UserAchievements")
                        .HasForeignKey("AchievementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Snackbox.Api.Models.User", "User")
                        .WithMany("UserAchievements")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Achievement");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Snackbox.Api.Models.Withdrawal", b =>
                {
                    b.HasOne("Snackbox.Api.Models.User", "User")
                        .WithMany("Withdrawals")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Snackbox.Api.Models.Achievement", b =>
                {
                    b.Navigation("UserAchievements");
                });

            modelBuilder.Entity("Snackbox.Api.Models.Barcode", b =>
                {
                    b.Navigation("Scans");
                });

            modelBuilder.Entity("Snackbox.Api.Models.Deposit", b =>
                {
                    b.Navigation("LinkedPayment");
                });

            modelBuilder.Entity("Snackbox.Api.Models.Product", b =>
                {
                    b.Navigation("Barcodes");

                    b.Navigation("Batches");
                });

            modelBuilder.Entity("Snackbox.Api.Models.ProductBatch", b =>
                {
                    b.Navigation("ShelvingActions");
                });

            modelBuilder.Entity("Snackbox.Api.Models.Purchase", b =>
                {
                    b.Navigation("Scans");
                });

            modelBuilder.Entity("Snackbox.Api.Models.User", b =>
                {
                    b.Navigation("Barcodes");

                    b.Navigation("Payments");

                    b.Navigation("Purchases");

                    b.Navigation("UserAchievements");

                    b.Navigation("Withdrawals");
                });
#pragma warning restore 612, 618
        }
    }
}
